name: Build Flet Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # 👈 نسخة مستقرة جداً لـ Flet      
      - run: |
          pip install flet==0.21.2 flet-flashlight flet-permission-handler          
          flet build apk --main app.py
      - uses: actions/upload-artifact@v4
        with:
          name: Flash-Success
          path: "**/*.apk"
