name: Build Flet Android APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          cache: true

      - name: Install Dependencies
        run: |
          pip install flet flet-cli flet-flashlight flet-permission-handler

      - name: Build APK (Detailed Mode)
        # أضفنا --verbose لرؤية تفاصيل الخطوات في سجلات GitHub
        run: |
          yes | flet build apk --module-name app --verbose

      - name: Locate and Move APK
        # سنقوم بالبحث عن الملف ونقله لمجلد واضح في الجذور لضمان الرفع
        run: |
          mkdir -p output
          find . -name "*.apk" -exec cp {} output/ \;
          ls -R output

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Flashlight-App-New
          path: output/*.apk
          if-no-files-found: error
